### ISSUE TITLE
HU05 - Consultar listado de coleccionistas

### ISSUE THREAD

**Issue by dhenaotoro** [dhenaotoro/app-movil-misw4203#4]
**Puntos de historia de usuario:** 2

**Actividades de la HU:**
<ul><li>Consumir servicio que consulta colecciones.</li><li>Construir pantalla para listar los coleccionistas consultados.</li></ul>

**Comment by IvanDSanchezC** [comment]
Mockups: https://www.figma.com/proto/2BeMovtGRtvIZObjiLRHch/Desarrollo-m%C3%B3vil?type=design&node-id=129-1497&t=3QafIcvGU8QiU6G6-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=52%3A446&show-proto-sidebar=1
