### ISSUE TITLE
HU02 - Consultar informacion detallada de un álbum

### ISSUE THREAD

**Issue by dhenaotoro** [dhenaotoro/app-movil-misw4203#5]
**Puntos de historia de usuario:** 2

**Actividades:**

<ul><li>Consumir servicio que consulta el detalle de un album seleccionado.</li><li>Construir pantalla para mostrar: <ol><li>Nombre</li><li>Imagen de caratula</li><li>Fecha de salida del mercado</li><li>Descripción</li><li>Genero</li><li>Casa discografica</li><li>Listado de tracks.</li><ol></li></ul>

**Comment by JsPinedas1** [comment]
Mockups: https://www.figma.com/proto/2BeMovtGRtvIZObjiLRHch/Desarrollo-m%C3%B3vil?type=design&node-id=147-1752&t=zxDASjhl0GP3fZWh-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=52%3A446
