### ISSUE TITLE
HU04 - Consultar la informacion detallada de un artista

### ISSUE THREAD

**Issue by dhenaotoro** [dhenaotoro/app-movil-misw4203#6]
**Puntos de historia de usuario:** 2

**Actividades de la HU:**

<ul><li>Consumir servicio que consulta el detalle de un artista seleccionado.</li><li>Construir pantalla para mostrar: Nombre, Imagen de artista, Descripción, Si es una banda se muestra fecha de formación, de lo contrario, si es persona, se muestra fecha de nacimiento.</li></ul>

**Comment by diegomartin81** [comment]
Mockups: https://www.figma.com/proto/2BeMovtGRtvIZObjiLRHch/Desarrollo-m%C3%B3vil?page-id=0%3A1&type=design&node-id=137-2137&viewport=712%2C-1114%2C0.5&t=ymnziHOeeQdGfcpU-1&scaling=min-zoom&starting-point-node-id=52%3A446&show-proto-sidebar=1&mode=design
