### ISSUE TITLE
HU06 - Consultar la información detallada de coleccionista

### ISSUE THREAD

**Issue by dhenaotoro** [dhenaotoro/app-movil-misw4203#7]
**Puntos de historia de usuario:** 2

**Actividades de la HU:**

<ul><li>Consumir servicio que consulta el detalle de un coleccionista seleccionado.</li><li>Construir pantalla para mostrar: Imagen del coleccionista, Nombre, Teléfono, Correo y Artistas favoritos.</li></ul>

**Comment by IvanDSanchezC** [comment]
Mockups: https://www.figma.com/proto/2BeMovtGRtvIZObjiLRHch/Desarrollo-m%C3%B3vil?type=design&node-id=129-1497&t=3QafIcvGU8QiU6G6-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=52%3A446&show-proto-sidebar=1
