### ISSUE TITLE
HU08 - Asociar tracks con un albúm

### ISSUE THREAD

**Issue by dhenaotoro** [dhenaotoro/app-movil-misw4203#8]
**Puntos de historia de usuario:** 3

**Actividades de la HU:**

<ul><li>Consumir servicio para consultar los tracks antes de mostrarlo en el Dropdown de lista de tracks.</li><li>Construir pantalla para asociar un track a un album el cual contiene: <ol><li>Dropdown para seleccionar el track.</li></ol></li><li>Consumir un servicio que permita asociar el track con el album</li></ul>

**Comment by JsPinedas1** [comment]
Mockups: https://www.figma.com/proto/2BeMovtGRtvIZObjiLRHch/Desarrollo-m%C3%B3vil?type=design&node-id=147-1752&t=zxDASjhl0GP3fZWh-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=52%3A446
